[package]
name = "thaw_tabster"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
tabster = { path = "../../tabster" }
leptos = { workspace = true }
web-sys = { version = "0.3.70" }