[package]
name = "thaw_tabster"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
tabster = { path = "../../tabster" }
keyborg = { path = "../../keyborg" }
leptos = { workspace = true }
web-sys = { version = "0.3.70" }
gloo-events = "0.2.0"
send_wrapper = "0.6"